version: "3.9"
services:
  apirest:
    build: .
    ports:
      - "8085:80"
    links:
      - myBDIntegration
  myBDIntegration:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=libreriaDB
      - MYSQL_ROOT_PASSWORD=nova
 # integracion:
  #  image: jenkins/jenkins
  #  ports: 
 #     - "8086:8080"
  #  links: 
 #     - apirest
